# Generated by Django 2.1.3 on 2018-11-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('official', models.BooleanField()),
                ('visibility', models.TextField()),
                ('guests_can_invite_others', models.BooleanField()),
                ('modified_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('participant_count', models.FloatField()),
                ('reason_for_private', models.TextField()),
                ('order_email_template', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_phone', models.TextField()),
                ('primary', models.BooleanField()),
                ('contact_email', models.TextField()),
                ('contact_family_name', models.TextField()),
                ('contact_given_name', models.TextField()),
                ('host_given_name', models.TextField()),
                ('timezone', models.TextField()),
                ('city', models.TextField()),
                ('locality', models.TextField()),
                ('state', models.TextField()),
                ('address_type', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('accuracy', models.TextField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('postal_code', models.TextField()),
                ('country', models.TextField()),
                ('modified_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('number_spaces_remaining', models.FloatField()),
                ('spaces_remaining', models.BooleanField()),
                ('name', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'locations',
            },
        ),
    ]
