# Generated by Django 2.1.3 on 2018-11-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evently', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE events RENAME TO _events_old;
            CREATE TABLE events
                (id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                status character varying,
                start_date timestamp without time zone,
                end_date timestamp without time zone,
                description character varying,
                official boolean,
                visibility character varying,
                guests_can_invite_others boolean,
                modified_date timestamp without time zone,
                created_date timestamp without time zone,
                participant_count numeric,
                reason_for_private character varying,
                order_email_template character varying,
                name character varying);
            INSERT INTO events
                (id,
                status,
                start_date,
                end_date,
                description,
                official,
                visibility,
                guests_can_invite_others,
                modified_date,
                created_date,
                participant_count,
                reason_for_private,
                order_email_template,
                name)
            SELECT
                id,
                status,
                start_date,
                end_date,
                description,
                official,
                visibility,
                guests_can_invite_others,
                modified_date,
                created_date,
                participant_count,
                reason_for_private,
                order_email_template,
                name
            FROM
                _events_old;
            """
        )
    ]
